AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'VisitorCount'
      AttributeDefinitions:
        - AttributeName: 'ID'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'ID'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST

  LambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'index.handler'
      Runtime: 'nodejs20.x'
      CodeUri: './'
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoDBTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: '/visitor-count'
            Method: 'get'
            RestApiId: !Ref ApiGatewayApi
            Auth:
              Cors:
                AllowMethods: "'GET,OPTIONS'"
                AllowHeaders: "'Content-Type'"
                AllowOrigin: "'*'"

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: 'Prod'
      Cors:
        AllowMethods: "'GET,OPTIONS'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

Outputs:
  ApiUrl:
    Description: 'API Gateway endpoint URL for Prod stage'
    Value: !Sub 'https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/visitor-count'