# Cloud Resume Workflow

name: Deploy Cloud Resume

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Set up AWS SAM CLI
        uses: aws-actions/setup-sam@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1  # Change to your region
      
      - name: Build and deploy SAM application
        working-directory: ./backend
        run: |
          # Create deployment bucket if it doesn't exist
          aws s3 mb s3://cloud-resume-sam-deployment-${{ secrets.AWS_REGION }} --region ${{ secrets.AWS_REGION }} || true
          
          # Build and deploy
          sam build
          sam deploy \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --stack-name cloud-resume-backend \
            --s3-bucket cloud-resume-sam-deployment-${{ secrets.AWS_REGION }} \
            --capabilities CAPABILITY_IAM \
            --region ${{ secrets.AWS_REGION }}

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'
          
      - name: Install dependencies
        working-directory: ./frontend
        run: |
          npm ci
          # If you're using npm < 7, use:
          # npm install
        
      - name: Build NextJS static site
        working-directory: ./frontend
        env:
          CI: false  # This prevents treating warnings as errors
        run: |
          npm run build
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Deploy to S3
        working-directory: ./frontend
        run: |
          aws s3 sync out/ s3://${{ secrets.S3_BUCKET }} --delete --exclude "images/"
          
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"